etitle: Komal Mudaliar # your name (or website title) here
logo: "/images/PhotoFunia-1734239994.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A seasoned Data Analyst with 7 years of  
  Industry Experience and a Master's degree in Computer Science. If you or someone you know is looking to hire a data analyst, let’s talk!
  <br><br>
  <a href="https://www.linkedin.com/in/komal-m/">View My LinkedIn Profile</a> 
 [<img src="images/Resume logo.png?raw=true"/>](https://www.linkedin.com/pulse/insights-from-human-resource-data-employee-turnover-komal-m-48e0e/?trackingId=6gpt%2FDaaRLKJuQFooKG1xQ%3D%3D)
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
